# Generated by Django 5.0.7 on 2024-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, upload_to='Media', verbose_name='Изображение'),
        ),
    ]
