# Generated by Django 5.0.7 on 2024-08-06 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shoes_price_shoes_sell_alter_shoes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.shoes')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
