# Generated by Django 5.0.7 on 2024-08-07 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imageshoes_options_alter_imageshoes_shoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageshoes',
            name='shoes',
        ),
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.imageshoes'),
        ),
    ]
